"""Agents-MD builder module: analyzes the vault's taxonomy/tags/frontmatter to draft AGENTS.md (requirement 3)."""

from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from .vault_io import VaultIO

MANUAL_NOTES_MARKER = "<!-- your manual notes below -->"


@dataclass(frozen=True)
class VaultTaxonomy:
    """Aggregate structural facts about the vault, gathered by scanning every note once."""

    folders: tuple[str, ...]
    tags: tuple[tuple[str, int], ...]
    frontmatter_keys: tuple[tuple[str, int], ...]
    note_count: int


class AgentsBuilder:
    """Scans the vault once and drafts AGENTS.md from what it actually finds (requirement 3)."""

    def __init__(self, vault: VaultIO, excluded_folders: frozenset[str] = frozenset()) -> None:
        self._vault = vault
        self._excluded_folders = excluded_folders

    def analyze(self) -> VaultTaxonomy:
        """Walk every note once and tally folders, tags, and frontmatter keys."""
        folders: set[str] = set()
        tag_counts: Counter[str] = Counter()
        key_counts: Counter[str] = Counter()
        note_count = 0

        for rel_path, note in self._vault.iter_notes(self._excluded_folders):
            note_count += 1
            parts = Path(rel_path).parts
            if len(parts) > 1:
                folders.add(parts[0])
            for key in note.metadata:
                key_counts[key] += 1
            for tag in note.metadata.get("tags") or []:
                tag_counts[str(tag)] += 1

        return VaultTaxonomy(
            folders=tuple(sorted(folders)),
            tags=tuple(tag_counts.most_common()),
            frontmatter_keys=tuple(key_counts.most_common()),
            note_count=note_count,
        )

    def build(self, vault_name: str, generated_date: str, existing_agents_md: Optional[str] = None) -> str:
        """Render AGENTS.md from a fresh taxonomy scan, preserving any hand-written notes section."""
        taxonomy = self.analyze()
        body = self._render(vault_name, generated_date, taxonomy)
        manual_notes = self._extract_manual_notes(existing_agents_md)
        if manual_notes:
            body = body.rstrip() + "\n\n" + manual_notes + "\n"
        return body

    @staticmethod
    def _extract_manual_notes(existing: Optional[str]) -> Optional[str]:
        """Pull out everything at/after the manual-notes marker so regeneration doesn't discard it."""
        if not existing or MANUAL_NOTES_MARKER not in existing:
            return None
        _, _, rest = existing.partition(MANUAL_NOTES_MARKER)
        return (MANUAL_NOTES_MARKER + rest).rstrip()

    def _render(self, vault_name: str, generated_date: str, taxonomy: VaultTaxonomy) -> str:
        """Format the taxonomy scan into the AGENTS.md template shape (see WORKING AGENT.md)."""
        folder_lines = "\n".join(f"- `{f}/`" for f in taxonomy.folders) or "- (no folders found yet)"
        tag_lines = ", ".join(f"`{t}` ({n})" for t, n in taxonomy.tags[:20]) or "(no tags found yet)"
        key_lines = ", ".join(f"`{k}` ({n})" for k, n in taxonomy.frontmatter_keys) or "(no frontmatter found yet)"

        return f"""# AGENTS.md — {vault_name} second brain

This file tells any AI agent how to work inside this Obsidian vault. Generated by the
vault analysis job on {generated_date} from {taxonomy.note_count} scanned notes.

## What this vault is
{taxonomy.note_count} notes across {len(taxonomy.folders)} top-level folders.

## Folder structure
{folder_lines}

## Tag vocabulary
{tag_lines}

## Frontmatter fields observed
{key_lines}

## AI-added content
Some notes carry an `> [!ai-fact-check]` callout near the end - Second Brain appends these
automatically each night after fact-checking that day's new notes against live web search.
They are never merged into the user's own prose, so they're always visually separable from
what the user actually wrote:
- Treat the callout's content as a note, not a correction already applied to the text above
  it - the user hasn't necessarily reviewed or acted on it yet.
- Never delete or edit a `> [!ai-fact-check]` callout; only the nightly pipeline writes these.
- If a callout and the note body disagree, say so plainly rather than picking one silently.

## Token-saving tips for AI tools
- This file is the map - read it before opening notes, not instead of grep/search on demand.
- Prefer a targeted read of the specific note(s) a question is about over scanning a whole
  folder; the folder/tag vocabulary above is usually enough to know where to look first.
- Don't re-summarize a note's full content back to the user if a short answer + a `[[link]]`
  to the source note will do.

## How to answer questions
- Answer only from what's in this vault. If it isn't covered, say so directly.
- Cite the specific note(s) as `[[wikilinks]]`, not "according to my search."
- No filler: skip disclaimers and hedging. State the answer, then the source.
- If two notes disagree, say that plainly and name both.

## What not to do
- Don't invent frontmatter fields, tags, or folders outside what's listed above.
- Don't rewrite a note's substance to "improve" it.
- Don't merge two notes without flagging it in the nightly report.

## Regeneration
Rebuilt by `worker/src/agents_md_builder.py` after any reorganization that changes the
folder taxonomy. Anything below this line is yours and survives regeneration.

---
{MANUAL_NOTES_MARKER}
"""
